import 'package:dio/dio.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:mockito/mockito.dart';

import 'package:holdyourbeer_flutter/core/network/api_client.dart';
import 'package:holdyourbeer_flutter/core/services/auth_service.dart';

// Manual Mock Classes for Testing
// In production, these would be generated by build_runner with @GenerateMocks

class MockDio extends Mock implements Dio {}

class MockFlutterSecureStorage extends Mock implements FlutterSecureStorage {}

class MockApiClient extends Mock implements ApiClient {}

class MockAuthService extends Mock implements AuthService {}

class MockResponse<T> extends Mock implements Response<T> {
  @override
  final int? statusCode;

  @override
  final T? data;

  @override
  final String? statusMessage;

  MockResponse({
    this.statusCode,
    this.data,
    this.statusMessage,
  });
}
